/* eslint-disable */
// @ts-nocheck
import Link from "next/link";
import useSWR from "swr";
import { ArrowRight, FileText } from "lucide-react";

import { EmptyState } from "@/components/EmptyState";
import { ErrorMessage } from "@/components/ErrorMessage";
import { ProgressIndicator } from "@/components/ProgressIndicator";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useMode } from "@/lib/mode-context";
import { fetcher } from "@/lib/api";

type ReportListItem = {
  date: string;
  summary?: string;
  top_strategies?: Array<{ strategy: string; pnl: number }>;
};

type ReportsResponse = {
  reports: ReportListItem[];
};

const truncate = (value: string, maxLength = 140) => {
  if (value.length <= maxLength) {
    return value;
  }
  return `${value.slice(0, maxLength)}…`;
};

export default function ReportsPage(): JSX.Element {
  const { isEasyMode } = useMode();
  const {
    data,
    error,
    isLoading,
    mutate: refetchReports,
  } = useSWR<ReportsResponse>("/api/reports?limit=30", fetcher, {
    revalidateOnFocus: false,
  });

  const reports = data?.reports ?? [];
  const latestReport = reports[0];

  return (
    <div className="space-y-8">
      <header className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Daily Reports</h1>
          <p className="text-sm text-muted-foreground">
            Review generated performance summaries, top strategies, and links to the stored artifacts.
          </p>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => {
            void refetchReports();
          }}
        >
          Refresh
        </Button>
      </header>

      {isLoading && (
        <ProgressIndicator message="Loading reports..." variant="spinner" />
      )}

      {error && (
        <ErrorMessage
          title="Failed to load reports"
          message={error instanceof Error ? error.message : "Unknown error"}
          error={error}
          onRetry={() => refetchReports()}
        />
      )}

      {latestReport ? (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base font-semibold">
              <Badge variant="secondary">Latest</Badge>
              {latestReport.date}
            </CardTitle>
            <CardDescription>{latestReport.summary || "No summary provided for this date."}</CardDescription>
          </CardHeader>
          <CardContent>
            <Link
              href={`/reports/${latestReport.date}`}
              className="inline-flex items-center gap-2 text-sm font-medium text-primary transition-colors hover:underline"
            >
              View full report
              <ArrowRight className="h-4 w-4" />
            </Link>
          </CardContent>
        </Card>
      ) : null}

      <section>
        <Card>
          <CardHeader>
            <CardTitle>Report History</CardTitle>
            <CardDescription>The 30 most recent reports generated by the bootstrap workflow.</CardDescription>
          </CardHeader>
          <CardContent>
            {reports.length ? (
              <ul className="space-y-3">
                {reports.map((report) => (
                  <li key={report.date}>
                    <Link
                      href={`/reports/${report.date}`}
                      className="flex items-start justify-between gap-4 rounded-lg border bg-muted/30 p-4 transition-colors hover:border-primary/50 hover:bg-primary/5"
                    >
                      <div>
                        <div className="flex items-center gap-2">
                          <FileText className="h-4 w-4 text-muted-foreground" />
                          <span className="font-medium text-foreground">{report.date}</span>
                        </div>
                        <p className="mt-1 text-sm text-muted-foreground">
                          {report.summary ? truncate(report.summary) : "No summary available."}
                        </p>
                      </div>
                      <Badge variant="outline">Open</Badge>
                    </Link>
                  </li>
                ))}
              </ul>
            ) : (
              <EmptyState
                variant="data"
                title={isEasyMode ? "No Reports Yet" : "No Reports Available"}
                description={
                  isEasyMode
                    ? "Daily performance reports will appear here once the system starts generating them. Complete the initial setup to get started."
                    : "No reports yet. Run the Phase 0 bootstrap workflow to generate the first report."
                }
              />
            )}
          </CardContent>
        </Card>
      </section>
    </div>
  );
}

